// Skin base embebida: interfaz neutra, sobria y orientada a la lectura.
// Los skins TXT pueden sobrescribir cada valor sin romper el fallback.

import type { ColorScheme } from "../types/appearance";

export type SkinVars = Record<string, string>;

export const DEFAULT_SKINS: Record<ColorScheme, Record<string, SkinVars>> = {
  light: {
    background: {
      background: "#ffffff",
      overlay: "none",
      blur: "0px",
      border: "1px solid #e6e6e3",
      radius: "0px",
      shadow: "none",
      text: "#2f2f2f",
      textDim: "#787774",
      accent: "#2383e2",
      font: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    button: {
      background: "transparent",
      backgroundHover: "#f1f1ef",
      text: "#37352f",
      textHover: "#2f2f2f",
      border: "1px solid transparent",
      borderHover: "#d9d9d7",
      radius: "7px",
      blur: "0px",
      shadow: "none",
      accent: "#2383e2",
    },
    note: {
      background: "#ffffff",
      backgroundHover: "#f7f7f5",
      text: "#2f2f2f",
      border: "1px solid #e6e6e3",
      radius: "10px",
      blur: "0px",
      shadow: "0 8px 28px rgba(15,15,15,0.10)",
      accent: "#2383e2",
    },
    sidebar: {
      background: "#f7f7f5",
      text: "#37352f",
      textDim: "#787774",
      itemHover: "#efefed",
      itemActive: "#e7e7e4",
      border: "1px solid #e6e6e3",
      radius: "0px",
      blur: "0px",
      shadow: "none",
      accent: "#2383e2",
    },
    input: {
      background: "#ffffff",
      text: "#2f2f2f",
      placeholder: "#9b9a97",
      border: "1px solid #e3e2e0",
      focus: "#2383e2",
      radius: "6px",
      blur: "0px",
      shadow: "none",
    },
    toolbar: {
      background: "#ffffff",
      text: "#2f2f2f",
      textDim: "#787774",
      border: "1px solid #e6e6e3",
      radius: "0px",
      blur: "0px",
      shadow: "none",
      accent: "#2383e2",
    },
  },
  dark: {
    background: {
      background: "#191919",
      overlay: "none",
      blur: "0px",
      border: "1px solid #30302f",
      radius: "0px",
      shadow: "none",
      text: "#e7e7e4",
      textDim: "#9b9b98",
      accent: "#5b9bd5",
      font: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    },
    button: {
      background: "transparent",
      backgroundHover: "#2b2b2a",
      text: "#e7e7e4",
      textHover: "#ffffff",
      border: "1px solid transparent",
      borderHover: "#464643",
      radius: "7px",
      blur: "0px",
      shadow: "none",
      accent: "#5b9bd5",
    },
    note: {
      background: "#202020",
      backgroundHover: "#292928",
      text: "#e7e7e4",
      border: "1px solid #343432",
      radius: "10px",
      blur: "0px",
      shadow: "0 10px 32px rgba(0,0,0,0.28)",
      accent: "#5b9bd5",
    },
    sidebar: {
      background: "#202020",
      text: "#e7e7e4",
      textDim: "#9b9b98",
      itemHover: "#292928",
      itemActive: "#343431",
      border: "1px solid #30302f",
      radius: "0px",
      blur: "0px",
      shadow: "none",
      accent: "#5b9bd5",
    },
    input: {
      background: "#252525",
      text: "#e7e7e4",
      placeholder: "#858580",
      border: "1px solid #3c3c39",
      focus: "#5b9bd5",
      radius: "6px",
      blur: "0px",
      shadow: "none",
    },
    toolbar: {
      background: "#202020",
      text: "#e7e7e4",
      textDim: "#9b9b98",
      border: "1px solid #30302f",
      radius: "0px",
      blur: "0px",
      shadow: "none",
      accent: "#5b9bd5",
    },
  },
};

// Alias compatible con consumidores que solo necesitan la paleta oscura.
export const DEFAULT_SKIN = DEFAULT_SKINS.dark;
